"""create databases

Revision ID: 8b4a20a5980a
Revises: 
Create Date: 2018-09-12 15:30:26.905506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4a20a5980a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airdrop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('trace_id', sa.String(length=50), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_symbol', 'airdrop', ['user_id', 'token'], unique=True)
    op.create_table('airdrop_supply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('asset_id', sa.String(length=50), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=16, scale=8), nullable=False),
    sa.Column('remaining', sa.DECIMAL(precision=16, scale=8), nullable=False),
    sa.Column('per_person', sa.DECIMAL(precision=16, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('payment',
    sa.Column('snapshot_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('ignore', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('vote',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('snapshot_id', sa.String(length=50), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('ignore', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'snapshot_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('payment')
    op.drop_table('airdrop_supply')
    op.drop_index('idx_user_symbol', table_name='airdrop')
    op.drop_table('airdrop')
    # ### end Alembic commands ###
