"""empty message

Revision ID: e985e7e5c0d6
Revises: 8b4a20a5980a
Create Date: 2018-09-12 17:05:50.856323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e985e7e5c0d6'
down_revision = '8b4a20a5980a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('product', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'product')
    # ### end Alembic commands ###
